export default {
    COLOR_PRIMARY: '#00ABAA',
    COLOR_SECONDARY: '#E32619',
    COLOR_GREEN: '#52AC62',
    COLOR_TEXT: '#4D4D4D',
    COLOR_BACKGROUND: '#F8F8F8',
    COLOR_LIGHTGREY: '#A3A3A3',
    COLOR_LIGHTERGREY: '#C5C5C5',
    COLOR_LIGHT_BLUE: '#D9FFFF',
}